[package]
name = "evn"
human_name = "Evenki"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.evn]
filename = "evn-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-evn"
platform = "windows"
uuid = "CDD14853-8AD0-4A3C-BC4D-FE3E991DD145"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.evn"
package = "speller-evn"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-evn-mso"
platform = "windows"
uuid = "6C9404F7-0611-4523-B563-F8AA7AFDD865"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-evn"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
